TEMPLATE = app
CONFIG += console c++14
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.cpp \
    Box2D/Collision/Shapes/b2CircleShape.cpp \
    Box2D/Collision/Shapes/b2PolygonShape.cpp \
    Box2D/Collision/b2BroadPhase.cpp \
    Box2D/Collision/b2CollideCircle.cpp \
    Box2D/Collision/b2CollidePolygon.cpp \
    Box2D/Collision/b2Collision.cpp \
    Box2D/Collision/b2Distance.cpp \
    Box2D/Collision/b2DynamicTree.cpp \
    Box2D/Collision/b2TimeOfImpact.cpp \
    Box2D/Common/b2BlockAllocator.cpp \
    Box2D/Common/b2Math.cpp \
    Box2D/Common/b2Settings.cpp \
    Box2D/Common/b2StackAllocator.cpp \
    Box2D/Dynamics/Contacts/b2CircleContact.cpp \
    Box2D/Dynamics/Contacts/b2Contact.cpp \
    Box2D/Dynamics/Contacts/b2ContactSolver.cpp \
    Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp \
    Box2D/Dynamics/Contacts/b2PolygonContact.cpp \
    Box2D/Dynamics/Contacts/b2TOISolver.cpp \
    Box2D/Dynamics/Joints/b2DistanceJoint.cpp \
    Box2D/Dynamics/Joints/b2FrictionJoint.cpp \
    Box2D/Dynamics/Joints/b2GearJoint.cpp \
    Box2D/Dynamics/Joints/b2Joint.cpp \
    Box2D/Dynamics/Joints/b2LineJoint.cpp \
    Box2D/Dynamics/Joints/b2MouseJoint.cpp \
    Box2D/Dynamics/Joints/b2PrismaticJoint.cpp \
    Box2D/Dynamics/Joints/b2PulleyJoint.cpp \
    Box2D/Dynamics/Joints/b2RevoluteJoint.cpp \
    Box2D/Dynamics/Joints/b2WeldJoint.cpp \
    Box2D/Dynamics/b2Body.cpp \
    Box2D/Dynamics/b2ContactManager.cpp \
    Box2D/Dynamics/b2Fixture.cpp \
    Box2D/Dynamics/b2Island.cpp \
    Box2D/Dynamics/b2World.cpp \
    Box2D/Dynamics/b2WorldCallbacks.cpp \
    GameObject.cpp \
    Player.cpp

LIBS += -L$$PWD/SFML/lib

CONFIG(release, debug|release): LIBS += -lsfml-audio -lsfml-graphics -lsfml-network -lsfml-window -lsfml-system
CONFIG(debug, debug|release): LIBS += -lsfml-audio-d -lsfml-graphics-d -lsfml-network-d -lsfml-window-d -lsfml-system-d

INCLUDEPATH += $$PWD/SFML/include
DEPENDPATH += $$PWD/SFML/include

HEADERS += \
    Box2D/Collision/Shapes/b2CircleShape.h \
    Box2D/Collision/Shapes/b2PolygonShape.h \
    Box2D/Collision/Shapes/b2Shape.h \
    Box2D/Collision/b2BroadPhase.h \
    Box2D/Collision/b2Collision.h \
    Box2D/Collision/b2Distance.h \
    Box2D/Collision/b2DynamicTree.h \
    Box2D/Collision/b2TimeOfImpact.h \
    Box2D/Common/b2BlockAllocator.h \
    Box2D/Common/b2Math.h \
    Box2D/Common/b2Settings.h \
    Box2D/Common/b2StackAllocator.h \
    Box2D/Dynamics/Contacts/b2CircleContact.h \
    Box2D/Dynamics/Contacts/b2Contact.h \
    Box2D/Dynamics/Contacts/b2ContactSolver.h \
    Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h \
    Box2D/Dynamics/Contacts/b2PolygonContact.h \
    Box2D/Dynamics/Contacts/b2TOISolver.h \
    Box2D/Dynamics/Joints/b2DistanceJoint.h \
    Box2D/Dynamics/Joints/b2FrictionJoint.h \
    Box2D/Dynamics/Joints/b2GearJoint.h \
    Box2D/Dynamics/Joints/b2Joint.h \
    Box2D/Dynamics/Joints/b2LineJoint.h \
    Box2D/Dynamics/Joints/b2MouseJoint.h \
    Box2D/Dynamics/Joints/b2PrismaticJoint.h \
    Box2D/Dynamics/Joints/b2PulleyJoint.h \
    Box2D/Dynamics/Joints/b2RevoluteJoint.h \
    Box2D/Dynamics/Joints/b2WeldJoint.h \
    Box2D/Dynamics/b2Body.h \
    Box2D/Dynamics/b2ContactManager.h \
    Box2D/Dynamics/b2Fixture.h \
    Box2D/Dynamics/b2Island.h \
    Box2D/Dynamics/b2TimeStep.h \
    Box2D/Dynamics/b2World.h \
    Box2D/Dynamics/b2WorldCallbacks.h \
    Box2D/Box2D.h \
    SFML/include/SFML/Audio/AlResource.hpp \
    SFML/include/SFML/Audio/Export.hpp \
    SFML/include/SFML/Audio/InputSoundFile.hpp \
    SFML/include/SFML/Audio/Listener.hpp \
    SFML/include/SFML/Audio/Music.hpp \
    SFML/include/SFML/Audio/OutputSoundFile.hpp \
    SFML/include/SFML/Audio/Sound.hpp \
    SFML/include/SFML/Audio/SoundBuffer.hpp \
    SFML/include/SFML/Audio/SoundBufferRecorder.hpp \
    SFML/include/SFML/Audio/SoundFileFactory.hpp \
    SFML/include/SFML/Audio/SoundFileReader.hpp \
    SFML/include/SFML/Audio/SoundFileWriter.hpp \
    SFML/include/SFML/Audio/SoundRecorder.hpp \
    SFML/include/SFML/Audio/SoundSource.hpp \
    SFML/include/SFML/Audio/SoundStream.hpp \
    SFML/include/SFML/Graphics/BlendMode.hpp \
    SFML/include/SFML/Graphics/CircleShape.hpp \
    SFML/include/SFML/Graphics/Color.hpp \
    SFML/include/SFML/Graphics/ConvexShape.hpp \
    SFML/include/SFML/Graphics/Drawable.hpp \
    SFML/include/SFML/Graphics/Export.hpp \
    SFML/include/SFML/Graphics/Font.hpp \
    SFML/include/SFML/Graphics/Glsl.hpp \
    SFML/include/SFML/Graphics/Glyph.hpp \
    SFML/include/SFML/Graphics/Image.hpp \
    SFML/include/SFML/Graphics/PrimitiveType.hpp \
    SFML/include/SFML/Graphics/Rect.hpp \
    SFML/include/SFML/Graphics/RectangleShape.hpp \
    SFML/include/SFML/Graphics/RenderStates.hpp \
    SFML/include/SFML/Graphics/RenderTarget.hpp \
    SFML/include/SFML/Graphics/RenderTexture.hpp \
    SFML/include/SFML/Graphics/RenderWindow.hpp \
    SFML/include/SFML/Graphics/Shader.hpp \
    SFML/include/SFML/Graphics/Shape.hpp \
    SFML/include/SFML/Graphics/Sprite.hpp \
    SFML/include/SFML/Graphics/Text.hpp \
    SFML/include/SFML/Graphics/Texture.hpp \
    SFML/include/SFML/Graphics/Transform.hpp \
    SFML/include/SFML/Graphics/Transformable.hpp \
    SFML/include/SFML/Graphics/Vertex.hpp \
    SFML/include/SFML/Graphics/VertexArray.hpp \
    SFML/include/SFML/Graphics/VertexBuffer.hpp \
    SFML/include/SFML/Graphics/View.hpp \
    SFML/include/SFML/Network/Export.hpp \
    SFML/include/SFML/Network/Ftp.hpp \
    SFML/include/SFML/Network/Http.hpp \
    SFML/include/SFML/Network/IpAddress.hpp \
    SFML/include/SFML/Network/Packet.hpp \
    SFML/include/SFML/Network/Socket.hpp \
    SFML/include/SFML/Network/SocketHandle.hpp \
    SFML/include/SFML/Network/SocketSelector.hpp \
    SFML/include/SFML/Network/TcpListener.hpp \
    SFML/include/SFML/Network/TcpSocket.hpp \
    SFML/include/SFML/Network/UdpSocket.hpp \
    SFML/include/SFML/System/Clock.hpp \
    SFML/include/SFML/System/Err.hpp \
    SFML/include/SFML/System/Export.hpp \
    SFML/include/SFML/System/FileInputStream.hpp \
    SFML/include/SFML/System/InputStream.hpp \
    SFML/include/SFML/System/Lock.hpp \
    SFML/include/SFML/System/MemoryInputStream.hpp \
    SFML/include/SFML/System/Mutex.hpp \
    SFML/include/SFML/System/NativeActivity.hpp \
    SFML/include/SFML/System/NonCopyable.hpp \
    SFML/include/SFML/System/Sleep.hpp \
    SFML/include/SFML/System/String.hpp \
    SFML/include/SFML/System/Thread.hpp \
    SFML/include/SFML/System/ThreadLocal.hpp \
    SFML/include/SFML/System/ThreadLocalPtr.hpp \
    SFML/include/SFML/System/Time.hpp \
    SFML/include/SFML/System/Utf.hpp \
    SFML/include/SFML/System/Vector2.hpp \
    SFML/include/SFML/System/Vector3.hpp \
    SFML/include/SFML/Window/Clipboard.hpp \
    SFML/include/SFML/Window/Context.hpp \
    SFML/include/SFML/Window/ContextSettings.hpp \
    SFML/include/SFML/Window/Cursor.hpp \
    SFML/include/SFML/Window/Event.hpp \
    SFML/include/SFML/Window/Export.hpp \
    SFML/include/SFML/Window/GlResource.hpp \
    SFML/include/SFML/Window/Joystick.hpp \
    SFML/include/SFML/Window/Keyboard.hpp \
    SFML/include/SFML/Window/Mouse.hpp \
    SFML/include/SFML/Window/Sensor.hpp \
    SFML/include/SFML/Window/Touch.hpp \
    SFML/include/SFML/Window/VideoMode.hpp \
    SFML/include/SFML/Window/Window.hpp \
    SFML/include/SFML/Window/WindowHandle.hpp \
    SFML/include/SFML/Window/WindowStyle.hpp \
    SFML/include/SFML/Audio.hpp \
    SFML/include/SFML/Config.hpp \
    SFML/include/SFML/GpuPreference.hpp \
    SFML/include/SFML/Graphics.hpp \
    SFML/include/SFML/Main.hpp \
    SFML/include/SFML/Network.hpp \
    SFML/include/SFML/OpenGL.hpp \
    SFML/include/SFML/System.hpp \
    SFML/include/SFML/Window.hpp \
    GameObject.hpp \
    Player.hpp
